apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
spec:
  replicas: 1
  selector:
    matchLabels:
      service: n8n-main
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: n8n-main
    spec:
      restartPolicy: Always
      containers:
        - name: main
          image: n8nio/n8n:latest
          args: ["start"]
          envFrom:
          - configMapRef:
              name: n8n-configmap-env
          resources:
            limits:
              cpu: "1.0"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
      volumeMounts:
        - name: oci-block-volume-n8n-pvc
          mountPath: /data/.n8n  # Caminho onde o volume será montado no container
    volumes:
      - name: oci-block-volume-n8n-pvc
        persistentVolumeClaim:
          claimName: oci-block-volume-n8n-pvc