apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      service: n8n-webhook
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: n8n-webhook
    spec:
      restartPolicy: Always
      containers:
        - name: webhook
          image: n8nio/n8n:latest
          args: ["webhook"]
          envFrom:
          - configMapRef:
              name: n8n-configmap-env
          resources:
            limits:
              cpu: "0.3"
              memory: "300Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"