apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      service: n8n-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: n8n-worker
    spec:
      restartPolicy: Always
      containers:
        - name: worker
          image: n8nio/n8n:latest
          args: ["worker", "--concurrency=50"]
          envFrom:
          - configMapRef:
              name: n8n-configmap-env
          resources:
            limits:
              cpu: "0.3"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"