apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Tamanho do PVC que será requisitado
  storageClassName: oci-bv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-marketplace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Tamanho do PVC que será requisitado
  storageClassName: oci-bv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi  # Tamanho do PVC que será requisitado
  storageClassName: oci-bv