apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # A quantidade de armazenamento solicitada (5 GB)
  storageClassName: longhorn  # O mesmo StorageClass que o PV