apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifests/01-rabbitmq-cluster-operador.yaml
- ./manifests/03-pvc-rabbitmq.yaml
- ./manifests/04-rabbitmq-cluster.yaml
- ./manifests/05-rabbitmq-service-nodeport.yaml
- ./manifests/06-rabbitmq-ingress.yaml