apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 3
  image: rabbitmq:3.11.10-management
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_management_agent
      - rabbitmq_web_dispatch
      - rabbitmq_peer_discovery_k8s
      - rabbitmq_prometheus
    additionalConfig: |
      cluster_formation.peer_discovery_backend = rabbitmq_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      vm_memory_high_watermark_paging_ratio = 0.85
      disk_free_limit.relative = 1.0
      cluster_formation.node_cleanup.interval = 10
      cluster_partition_handling = autoheal
      queue_master_locator = min-masters
      loopback_users = none
      default_user = jetsales
      default_pass = jetsales
      prometheus.return_per_object_metrics = false
      prometheus.path = /metrics
    advancedConfig: ""
  statefulSet:
    volumeClaimTemplates:
      - metadata:
          name: rabbitmq-pvc
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi  # Garantir que o PVC com 5GB será usado
          storageClassName: oci-bv
    podManagementPolicy: OrderedReady
    template:
      spec:
        containers:
          - name: rabbitmq
            resources:
            limits:
              cpu: "2.0"
              memory: "2024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
        affinity:
          podAffinity: {}  # Não há afinidade de pod específica aqui
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rabbitmq
                topologyKey: kubernetes.io/hostname  # Isso garante que os pods não sejam agendados no mesmo nó